Update diabetes_regression-cd.yml for Azure Pipelines

diff --git a/.pipelines/diabetes_regression-cd.yml b/.pipelines/diabetes_regression-cd.yml
--- a/.pipelines/diabetes_regression-cd.yml
+++ b/.pipelines/diabetes_regression-cd.yml
@@ -77,8 +77,58 @@ stages:
               inlineScript: |
                 set -e # fail on error
                 export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-                python -m ml_service.util.smoke_test_scoring_service --type ACI --service "$(ACI_DEPLOYMENT_NAME)"
+                python -m ml_service.util.smoke_test_scoring_service --type ACI --service "$(ACI_DEPLOYMENT_NAME_DEV)"
 
+- stage: 'Deploy_ACI_tST'
+  displayName: 'Deploy to ACI to tST'
+  condition: variables['ACI_DEPLOYMENT_NAME_TST']
+  jobs:
+  # - job: "Deploy_ACI"
+  - deployment: "Deploy_ACI_Tst"
+    displayName: "Deploy to ACI to Tst"
+    container: mlops
+    timeoutInMinutes: 0
+    environment: 'tst'
+    strategy:
+      runOnce:
+        deploy:         
+          steps:
+          - download: none
+          - template: diabetes_regression-get-model-id-artifact-template.yml
+            parameters:
+              projectId: '$(resources.pipeline.model-train-ci.projectID)'
+              pipelineId: '$(resources.pipeline.model-train-ci.pipelineID)'
+              artifactBuildId: ${{ parameters.artifactBuildId }}
+          - task: AzureCLI@1
+            displayName: 'Install AzureML CLI'
+            inputs:
+              azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+              scriptLocation: inlineScript
+              workingDirectory: $(Build.SourcesDirectory)
+              inlineScript: 'az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.27.0-py3-none-any.whl --yes'
+          - task: AzureCLI@1
+            displayName: "Deploy to ACI (CLI)"
+            inputs:
+              azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+              scriptLocation: inlineScript
+              workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring
+              inlineScript: |
+                set -e # fail on error
+                
+                az ml model deploy --name $(ACI_DEPLOYMENT_NAME_TST) --model '$(MODEL_NAME):$(get_model.MODEL_VERSION)' \
+                --ic inference_config.yml \
+                --dc deployment_config_aci.yml \
+                -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
+                --overwrite -v
+          - task: AzureCLI@1
+            displayName: 'Smoke test'
+            inputs:
+              azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+              scriptLocation: inlineScript
+              inlineScript: |
+                set -e # fail on error
+                export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+                python -m ml_service.util.smoke_test_scoring_service --type ACI --service "$(ACI_DEPLOYMENT_NAME_TST)"
 
 - stage: 'Deploy_AKS'
   displayName: 'Deploy to AKS'
